version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile   # Caso você renomeie o arquivo; se não, mantenha "dockerfile"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: env.dev  # Carrega as variáveis de ambiente do arquivo de ambiente

  # Exemplo de serviço para um banco de dados PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: bookstore_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: