# Use uma imagem base maior e mais compatível
FROM ubuntu:latest

# Adicione um script shell que imprime "Hello World"
RUN echo 'echo "Hello World"' > /hello.sh

# Torne o script executável
RUN chmod +x /hello.sh

# Defina o script como o ponto de entrada
ENTRYPOINT ["/bin/sh", "/hello.sh"]